[package]
name = "irlab"
version = "0.1.0"
authors = ["wzh99 <wzh1999_frog@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
